# Generated by Django 4.0.1 on 2023-12-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_language', models.CharField(max_length=30)),
                ('target_language', models.CharField(max_length=30)),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
